# ??????MySQL8.0+ ???cj???5.7?com.mysql.jdbc.Driver?
jdbc.driver=com.mysql.cj.jdbc.Driver
# ???URL??????????cyber_stone_video???????SSL?????????
jdbc.url=jdbc:mysql://localhost:3306/cyber_stone_video?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
# ?????
jdbc.username=root
# ????????????????
jdbc.password=Lzh123126129
# ???????????????
jdbc.pool.coreSize=5
jdbc.pool.maxSize=10
jdbc.pool.timeout=3000

# Redis??
redis.host=localhost
redis.port=6379
redis.password=
redis.database=0
redis.maxTotal=50
redis.maxIdle=10

